name: Apple Job Tracker

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: python apple_jobs.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Apple Job Tracker Results
          to: ogundele01@gmail.com
          from: Apple Job Tracker
          body: |
            Apple job search completed.
            Check attached jobs.json file.
          attachments: jobs.json
